name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    concurrency:
      group: test-${{ github.ref_name }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prettier
        run: npm run fmt

      - name: ESLint
        run: npm run lint

      - name: Typescript
        run: npm run ts:check

      - name: Unit Tests And Coverage
        run: npm run test:coverage
